language: go
  go:
    - "1.10"

before_install:
  - curl -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 > /bin/dep
  - chmod a+x /bin/dep

script:
  - dep ensure -v
  - go test -v ./...
